FROM node:16

WORKDIR /app

COPY ./package.json ./package.json
COPY ./index.js ./index.js
COPY ./.env ./.env

COPY ./config ./config
COPY ./controllers ./controllers
COPY ./models ./models
COPY ./routes ./routes
COPY ./services ./services

COPY ./businesses.json ./businesses.json
COPY ./collections.json /collections.json

RUN npm install 

EXPOSE 3001

CMD npm run dev