services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3001:3001"